apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: java-kubernetes
  name: java-kubernetes
  namespace: default
spec:
  replicas: 3
  minReadySeconds: 45 
  selector:
    matchLabels:
      app: java-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-kubernetes
    spec:
      containers:
      - image: vishal210893/kubernetes:java_kubernetes_5
        imagePullPolicy: IfNotPresent
        name: kubernetes
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-kubernetes
  name: java-kubernetes
  namespace: default
spec:
  ports:
  - nodePort: 31995
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-kubernetes
  sessionAffinity: None
  type: LoadBalancer
