apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-17T19:13:55Z"
  labels:
    app: java-kubernetes
  name: java-kubernetes
  namespace: default
  resourceVersion: "27184"
  selfLink: /api/v1/namespaces/default/services/java-kubernetes
  uid: 94f8dfc9-80df-11ea-8b61-42010a800119
spec:
  clusterIP: 10.99.9.82
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31995
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-kubernetes
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 104.198.222.242
