apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4"},"creationTimestamp":"2020-04-17T19:12:45Z","generation":6,"labels":{"app":"java-kubernetes"},"name":"java-kubernetes","namespace":"default","resourceVersion":"49683","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/java-kubernetes","uid":"6b6c6c82-80df-11ea-8b61-42010a800119"},"spec":{"progressDeadlineSeconds":600,"replicas":5,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"java-kubernetes"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"java-kubernetes"}},"spec":{"containers":[{"image":"vishal210893/kubernetes:java_kubernetes_5","imagePullPolicy":"IfNotPresent","name":"kubernetes","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2020-04-17T20:24:35Z","lastUpdateTime":"2020-04-17T20:24:35Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-04-17T19:12:45Z","lastUpdateTime":"2020-04-17T20:59:05Z","message":"ReplicaSet \"java-kubernetes-56f8f4b5c7\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":6,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2020-04-17T19:12:45Z"
  generation: 7
  labels:
    app: java-kubernetes
  name: java-kubernetes
  namespace: default
  resourceVersion: "70213"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/java-kubernetes
  uid: 6b6c6c82-80df-11ea-8b61-42010a800119
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: java-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-kubernetes
    spec:
      containers:
      - image: vishal210893/kubernetes:java_kubernetes_5
        imagePullPolicy: IfNotPresent
        name: kubernetes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2020-04-17T19:12:45Z"
    lastUpdateTime: "2020-04-17T20:59:05Z"
    message: ReplicaSet "java-kubernetes-56f8f4b5c7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-17T22:37:03Z"
    lastUpdateTime: "2020-04-17T22:37:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
